version: '3'
services:

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  db:
    image: "redis:alpine"
    hostname: redis       # host name in the RestWebService application
    ports:
     - "6379:6379"        
     
  rest-web-service:
    build: ./RestWebService
    ports: 
      - 8181:8080
    links:
      - "db:redis"
      
  presentation:
    image: php:apache
    volumes: 
      - ./presentation:/var/www/html  # unable html updating without restarting docker compose
    ports:
      - 8282:80          # use http://localhost:8282/ in a web browser
